### ISSUE TITLE
I have a fix for you...

### ISSUE THREAD

**Issue by justjim1220** [mykle1/MMM-PC-Stats#1]
you have this in your js file:
`
/*      // Can't get the dynamically created div's to work
        // Hard coding 8 if statements below in the meantime
        // need to map "Core 0" to just [0] for 8 "Cores"
        
        for (var i = 0, len = Sensors['coretemp-isa-0000']['ISA adapter'].length; i < len; i++) {
            var newElement = document.createElement("div");
            newElement.classList.add("small", "bright", "coreNameTemp");
            newElement.innerHTML = Sensors['coretemp-isa-0000']['ISA adapter'][i].name + " &nbsp  @  &nbsp " 
								 + Sensors['coretemp-isa-0000']['ISA adapter'][i].value + "&deg;C";
            wrapper.appendChild(newElement);
        }
*/
`

the following is the fix I think you are looking for:
`
for (var i = 0, len = Stats.cpu.threads.length; i < len; i++) {

		var Element = document.createElement("span");
		Element.classList.add("large", "bright", "usage");
		Element.innerHTML = Stats.cpu.threads[i].name + "&nbsp @ &nbsp" + Number(Math.round(Stats.cpu.threads[i].usage+"e2")+"e-2") + "%" + " &nbsp&nbsp " + " ";

        // Check if core0 has temp sensor
		 var core0TempCheck = Sensors["coretemp-isa-0000"]['ISA adapter']['Core 0'];
		if (typeof core0TempCheck !== 'undefined'){

			// core0Temp
			var core0Temp = document.createElement("span");
			core0Temp.classList.add("large", "bright", "core0Temp");
			core0Temp.innerHTML = "Temp: " + " &nbsp " + Sensors["coretemp-isa-0000"]["ISA adapter"]["Core 0"].value + "&deg;C"; + "<br>";
			Element.appendChild(core0Temp);
		}
		wrapper.appendChild(Element);
	}
`
no need for 8 separate entries

**Comment by mykle1** [comment]
Thanks Jim, although that didn't really need to be fixed. It was just a note to myself. If the module wasn't working I would certainly add the PR. Now, if you really want to FIX something in this module, make it recognize the components of whatever device it runs on so the code doesn't break when it finds a different maker. Remember? Thanks bro

**Comment by mykle1** [comment]
I was curious as to what your fix was going to do. Here is what is what it looks like.

![jj](https://user-images.githubusercontent.com/25211804/48668287-879e1880-eab7-11e8-85e4-1de7331d5b0d.png)

**Comment by cowboysdude** [comment]
I don't like the way it looks at me... it tells me things I don't like, it's scary.  Can you make the font comic sans and 100 times bigger?

**Comment by mykle1** [comment]
You psycho sick son of a bitch! hahahaha
